# 集群初始化后请勿随意修改配置, 否则可能导致无法正常运行!!!
# 远程节点保存脚本的目录, 请确保其父目录一定存在(默认 /opt/k8sRemoteScript)
remoteScriptDir: ""
cluster:
  kubernetesVersion: "1.28.6"
  # 对应 kubeadm 中 controlPlaneEndpoint(默认 master1 address, port 6443)
  controlPlaneAddress: ""
  controlPlanePort:
  # 镜像仓库地址
  imageRepository: ""
  # kubeadm 签发证书(默认 true), false --> 自签证书(default 50Y), 升级集群不更新组件证书
  kubeadmSignCertificate: ""
container:
  criName: "containerd"
  # 私有仓库地址, 比如 http://192.168.10.38
  privateRepository: ""
nodes:
  # 所有节点统一账号(默认 root), 非 root 用户必须能运行 sudo 以及注意 remoteScriptDir 权限问题
  nodeUser: ""
  # 所有节点统一密码(默认为空, 控制台输入)
  nodePassword: ""
  # 第一个初始化集群的 master 节点(必须)
  master1:
    domain: m1.k8s
    address: "192.168.11.101"
  # 其他 master 节点
  master:
  - domain: m2.k8s
    address: "192.168.11.102"
  - domain: m3.k8s
    address: "192.168.11.103"
  # 工作节点
  work:
  - domain: w1.k8s
    address: "192.168.11.104"
