version: "3.8"
services:
  nginx:
    image: nginx:1.18.0
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 6443:6443
    networks:
      - net
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    restart: always

networks:
  net: